/* Pathway to B1 — course "en", Spanish (es) support overlay.
   Generated by tools/split-curriculum.js (i18n plan Phase 3).
   Plain JS, no JSX: a one-line window.PTB_COURSES wrapper around a pure
   JSON literal, loaded via <script src> AFTER courses/en.core.js.

   Translations are keyed by topic id + ITEM id from the core — never by
   array index.
   ID STABILITY RULE: every content item carries a short stable id
   (theory t*, examples e*, flashcards f*, quiz q*, placement p*).
   Support overlays key translations by topic id + ITEM id — never by
   array index. Future insertions MUST mint NEW ids (t4, e9, f11, ...);
   NEVER renumber or reuse existing ids, even when inserting mid-array
   or deleting items. */
window.PTB_COURSES.en.support = window.PTB_COURSES.en.support || {};
window.PTB_COURSES.en.support.es = {
  "name": "Español",
  "topics": {
    "a1-greet": {
      "title": "Saludos y presentaciones",
      "theory": {
        "t1": {
          "heading": "Saludos formales e informales",
          "body": "Los saludos en inglés dependen de la situación. Usa <strong>Hello</strong>, <strong>Good morning</strong>, <strong>Good afternoon</strong> o <strong>Good evening</strong> en situaciones formales — con desconocidos, en el trabajo o al conocer a alguien por primera vez. Usa <strong>Hi</strong> o <strong>Hey</strong> con amigos y familia. <em>Good morning</em> se usa antes del mediodía; <em>Good afternoon</em> desde el mediodía hasta alrededor de las 6 de la tarde; <em>Good evening</em> después de esa hora."
        },
        "t2": {
          "heading": "Presentarte a ti mismo",
          "body": "Para presentarte di: <strong>My name is [nombre]</strong> o <strong>I'm [nombre]</strong>. Puedes añadir de dónde eres: <strong>I'm from Chile / London / Spain</strong>. Para preguntar el nombre de alguien di: <strong>What's your name?</strong> o <strong>What is your name, please?</strong> Para preguntar de dónde es alguien: <strong>Where are you from?</strong> Para preguntar la edad: <strong>How old are you? — I'm twenty-five years old.</strong>"
        },
        "t3": {
          "heading": "Frases útiles para los primeros encuentros",
          "body": "Cuando conoces a alguien por primera vez di <strong>Nice to meet you</strong> o <strong>Pleased to meet you</strong>. La otra persona responde: <strong>Nice to meet you too!</strong> Para despedirte: <strong>Goodbye</strong> (formal), <strong>Bye</strong> (informal), <strong>See you later / See you tomorrow</strong> o <strong>Take care</strong>. Usa siempre <strong>please</strong> para ser cortés al hacer peticiones y <strong>thank you</strong> / <strong>thanks</strong> para mostrar gratitud."
        }
      },
      "examples": {
        "e1": "¡Hola! Me llamo Sarah. Encantada de conocerte.",
        "e2": "Buenos días, Sr. García. ¿Cómo está usted hoy?",
        "e3": "¡Hola! Soy Tom. Soy de Londres.",
        "e4": "¿Cómo te llamas? — Me llamo Anna.",
        "e5": "¿De dónde eres? — Soy de Chile.",
        "e6": "¿Cuántos años tienes? — Tengo veinticinco años.",
        "e7": "Esta es mi colega, Maria. ¡Encantado de conocerte!",
        "e8": "¡Adiós! ¡Hasta mañana!"
      },
      "flashcards": {
        "f1": "Hola",
        "f2": "Adiós",
        "f3": "Buenos días",
        "f4": "Buenas noches (saludo al llegar)",
        "f5": "¿Cómo te llamas?",
        "f6": "Me llamo…",
        "f7": "Encantado/a de conocerte",
        "f8": "¿De dónde eres?",
        "f9": "Gracias",
        "f10": "Por favor"
      },
      "quiz": {
        "q1": "'Good morning' es el saludo formal. 'Hey', 'Yo' y 'What's up?' son informales.",
        "q2": "Decimos 'My name is John.' Es la forma estándar de presentarte.",
        "q3": "'Nice to meet you' es un saludo para los primeros encuentros.",
        "q4": "'What's your name?' es la pregunta correcta. Las demás no son inglés gramatical.",
        "q5": "'Pleased to meet you' expresa alegría al conocer a alguien por primera vez."
      }
    },
    "a1-num": {
      "title": "Números, días y la hora",
      "theory": {
        "t1": {
          "heading": "Números cardinales",
          "body": "Aprende primero los números <strong>1–20</strong>: one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, fifteen, sixteen, seventeen, eighteen, nineteen, twenty. Luego las decenas: <strong>twenty, thirty, forty, fifty, sixty, seventy, eighty, ninety, one hundred</strong>. Para números como 21, combínalos: <strong>twenty-one</strong> (usa siempre un guion al escribir: twenty-one, thirty-five, etc.)."
        },
        "t2": {
          "heading": "Los días de la semana",
          "body": "Los siete días son: <strong>Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday</strong>. En el Reino Unido la semana empieza el lunes. <strong>Weekend</strong> = sábado y domingo. <strong>Weekday</strong> = de lunes a viernes. Usa <em>on</em> con los días: <strong>on Monday</strong>, <strong>on Fridays</strong> (= todos los viernes). Los días de la semana siempre se escriben con mayúscula en inglés."
        },
        "t3": {
          "heading": "Decir la hora",
          "body": "Para las horas en punto di: <strong>It's three o'clock.</strong> Para los 30 minutos pasados: <strong>It's half past three.</strong> Para los 15 minutos pasados: <strong>It's quarter past three.</strong> Para los 15 minutos antes de la hora: <strong>It's quarter to four.</strong> Para otros minutos: <strong>It's ten past three / It's twenty to four.</strong> En la escritura formal puedes usar el reloj de 24 horas: 14:30. Pregunta siempre: <strong>What time is it?</strong> o <strong>What's the time?</strong>"
        }
      },
      "examples": {
        "e1": "Son las tres en punto. La tienda abre a las nueve.",
        "e2": "Hoy es lunes. Mañana es martes.",
        "e3": "Hay siete días en una semana.",
        "e4": "Me despierto a las siete y media todas las mañanas.",
        "e5": "La reunión es el viernes a las diez menos cuarto.",
        "e6": "Mi cumpleaños es el quince de junio.",
        "e7": "Cien estudiantes estudian inglés aquí.",
        "e8": "Son las dos y veinticinco de la tarde."
      },
      "flashcards": {
        "f1": "¿Qué hora es?",
        "f2": "Las tres y media (3:30)",
        "f3": "Y cuarto",
        "f4": "Menos cuarto",
        "f5": "Lunes",
        "f6": "Miércoles",
        "f7": "Viernes",
        "f8": "Fin de semana",
        "f9": "Veintiuno",
        "f10": "Cien"
      },
      "quiz": {
        "q1": "Los números entre 21 y 99 se escriben con guion: thirty-five.",
        "q2": "'Half past three' = 3:30. El minutero está a la mitad después de la hora.",
        "q3": "El orden es Mon, Tue, Wed, Thu, Fri, Sat, Sun.",
        "q4": "'Quarter to four' = 15 minutos antes de las 4 = 3:45.",
        "q5": "'What time is it, please?' es la forma cortés y gramaticalmente correcta de preguntar."
      }
    },
    "a1-fam": {
      "title": "La familia y las personas",
      "theory": {
        "t1": {
          "heading": "Miembros de la familia",
          "body": "Vocabulario básico de la familia: <strong>mother / mum / mom</strong> (madre, informal), <strong>father / dad</strong> (padre, informal), <strong>brother</strong> (hermano), <strong>sister</strong> (hermana), <strong>grandmother / grandma</strong> (abuela), <strong>grandfather / grandpa</strong> (abuelo), <strong>aunt</strong> (tía), <strong>uncle</strong> (tío), <strong>cousin</strong> (primo/a), <strong>son</strong> (hijo), <strong>daughter</strong> (hija), <strong>husband</strong> (esposo), <strong>wife</strong> (esposa). Palabras colectivas: <strong>parents</strong> (padres), <strong>children</strong> (hijos, plural de child), <strong>grandparents</strong> (abuelos), <strong>siblings</strong> (hermanos). Familia extendida: <strong>niece</strong> (sobrina), <strong>nephew</strong> (sobrino)."
        },
        "t2": {
          "heading": "Describir personas con 'Have' y 'Be'",
          "body": "Usa <strong>have</strong> para describir características físicas: <strong>She has brown hair</strong> (tiene el pelo castaño). <strong>He has blue eyes</strong> (tiene los ojos azules). <strong>They have two children</strong> (tienen dos hijos). Usa <strong>be</strong> para la edad, el tamaño y el carácter: <strong>She is tall</strong> (es alta). <strong>He is young</strong> (es joven). <strong>She is kind</strong> (es amable). Adjetivos útiles: <em>tall (alto), short (bajo), young (joven), old (viejo), kind (amable), funny (gracioso), quiet (callado), loud (ruidoso), clever (listo), friendly (simpático)</em>."
        },
        "t3": {
          "heading": "Los posesivos",
          "body": "Para mostrar posesión, añade <strong>'s</strong> a un nombre: <strong>Anna's brother</strong> (el hermano de Anna), <strong>Tom's mother</strong> (la madre de Tom). Usa los adjetivos posesivos: <strong>my (mi), your (tu), his (su, de él), her (su, de ella), its (su, de algo), our (nuestro), their (su, de ellos).</strong> Ejemplos: <em>My parents are from Sweden. Her grandfather is 80. Their children go to school here.</em> Nota: NO añadas apóstrofo a los adjetivos posesivos — escribe <em>its</em>, no <em>it's</em> (que significa 'it is')."
        }
      },
      "examples": {
        "e1": "Tengo un hermano y dos hermanas.",
        "e2": "Mi madre es profesora. Tiene el pelo castaño.",
        "e3": "Su abuelo tiene ochenta años.",
        "e4": "Tenemos tres hijos: dos hijos varones y una hija.",
        "e5": "Esta es mi esposa, Julia. Es de España.",
        "e6": "Mis padres viven en un pueblo pequeño cerca de Valparaíso.",
        "e7": "Él tiene un primo en Australia.",
        "e8": "Nuestros tíos nos visitan cada Navidad."
      },
      "flashcards": {
        "f1": "Madre",
        "f2": "Padre",
        "f3": "Hermano",
        "f4": "Hermana",
        "f5": "Abuela",
        "f6": "Hijo",
        "f7": "Hija",
        "f8": "Esposo / Marido",
        "f9": "Esposa / Mujer",
        "f10": "Sobrina"
      },
      "quiz": {
        "q1": "'Have' se usa para describir características físicas como el color de ojos y el pelo.",
        "q2": "La madre de tu madre es tu abuela (grandmother).",
        "q3": "'Their' es el adjetivo posesivo de 'they'. 'They' es un pronombre de sujeto.",
        "q4": "'Child' tiene un plural irregular: children. Nunca 'childs' ni 'childrens'.",
        "q5": "La hija de tu hermano o hermana es tu sobrina (niece)."
      }
    },
    "a1-now": {
      "title": "Qué está pasando ahora mismo",
      "theory": {
        "t1": {
          "heading": "Presente continuo — pasando ahora",
          "body": "Usa el <strong>presente continuo</strong> para acciones que pasan ahora mismo: <strong>am / is / are + verbo con -ing</strong>. <em>I am eating</em> (estoy comiendo). <em>She is working. They are watching TV.</em> Negativo: <em>He isn't sleeping.</em> Pregunta: <em>Are you listening?</em> Cambios de ortografía: los verbos terminados en <em>-e</em> la pierden (<em>make → making, write → writing</em>); los verbos cortos que terminan en una vocal + una consonante doblan la consonante (<em>sit → sitting, run → running, swim → swimming</em>)."
        },
        "t2": {
          "heading": "There is / There are (hay)",
          "body": "Para decir que algo existe, usa <strong>there is</strong> con sustantivos en singular y <strong>there are</strong> con plurales: <em>There is a park near my house</em> (hay un parque cerca de mi casa). <em>There are three cafés in this street.</em> Negativos: <strong>there isn't</strong> / <strong>there aren't</strong>: <em>There isn't a bank here. There aren't any buses at night.</em> Preguntas: <strong>Is there…? / Are there…?</strong> — <em>Is there a pharmacy near here? — Yes, there is. / No, there isn't.</em>"
        },
        "t3": {
          "heading": "Preguntas con do / does — hábitos vs ahora",
          "body": "El <strong>presente simple</strong> describe hábitos y rutinas. Forma preguntas con <strong>do / does</strong>: <em>Do you work on Saturdays?</em> (¿Trabajas los sábados?) <em>Does she live here? Does he speak English?</em> Usa <strong>does</strong> con <em>he / she / it</em>, y deja el verbo principal en su forma base (<em>Does she live</em>, no <em>Does she lives</em>). Contrasta los dos tiempos: presente simple = hábitos (<em>I drink coffee every day</em>); presente continuo = ahora (<em>I am drinking coffee right now</em>)."
        }
      },
      "examples": {
        "e1": "Estoy estudiando inglés ahora mismo.",
        "e2": "Ella está preparando el almuerzo en la cocina.",
        "e3": "¡Mira! Está lloviendo.",
        "e4": "Hay un supermercado cerca de mi casa.",
        "e5": "Hay dos bancos en esta calle, pero no hay farmacia.",
        "e6": "¿Hay un paradero de micros cerca de aquí? — Sí, hay.",
        "e7": "¿Ella vive en Valparaíso? — Sí.",
        "e8": "Normalmente tomo té, pero hoy estoy tomando café."
      },
      "flashcards": {
        "f1": "am / is / are + verbo con -ing",
        "f2": "Para acciones que pasan ahora mismo",
        "f3": "Ahora mismo",
        "f4": "Hay… (una cosa, singular)",
        "f5": "Hay… (varias cosas, plural)",
        "f6": "No hay… (singular)",
        "f7": "¿Hay un banco cerca de aquí?",
        "f8": "¿Trabajas? (pregunta con 'do')",
        "f9": "¿Ella vive aquí? (pregunta con 'does')",
        "f10": "sitting (con doble t)"
      },
      "quiz": {
        "q1": "El presente continuo (is raining) se usa para acciones que pasan ahora. 'Rains' es presente simple, para hábitos.",
        "q2": "'There are' se usa con sustantivos en plural como 'two banks'. 'There is' es solo para singular.",
        "q3": "Los verbos terminados en -e pierden la -e antes de -ing: make → making.",
        "q4": "Las preguntas en presente simple con he/she/it usan 'does', y el verbo principal queda en su forma base: Does she work…?",
        "q5": "El presente simple (I drink coffee every morning) describe un hábito. Las otras tres son presente continuo — acciones en progreso ahora."
      }
    },
    "a1-food": {
      "title": "Comida y bebida",
      "theory": {
        "t1": {
          "heading": "Vocabulario común de comida y bebida",
          "body": "Palabras clave de comida: <strong>bread</strong> (pan), <strong>butter</strong> (mantequilla), <strong>milk</strong> (leche), <strong>cheese</strong> (queso), <strong>eggs</strong> (huevos), <strong>meat</strong> (carne), <strong>chicken</strong> (pollo), <strong>fish</strong> (pescado), <strong>vegetables</strong> (verduras), <strong>fruit</strong> (fruta), <strong>rice</strong> (arroz), <strong>pasta</strong>, <strong>soup</strong> (sopa), <strong>salad</strong> (ensalada), <strong>cake</strong> (pastel). Bebidas: <strong>water</strong> (agua), <strong>coffee</strong> (café), <strong>tea</strong> (té), <strong>juice</strong> (jugo), <strong>beer</strong> (cerveza), <strong>wine</strong> (vino), <strong>lemonade</strong> (limonada). Comidas: <strong>breakfast</strong> (desayuno), <strong>lunch</strong> (almuerzo), <strong>dinner / supper</strong> (cena). <em>Snack</em> = una pequeña cantidad de comida entre comidas."
        },
        "t2": {
          "heading": "Pedir comida con cortesía",
          "body": "En una cafetería o restaurante usa estas frases corteses: <strong>I would like… / I'd like…</strong> (lo más cortés), <strong>Can I have…?</strong> (común), <strong>Could I have…?</strong> (muy cortés). Ejemplos: <em>I'd like a coffee with milk, please. Could I have the menu? Can I have some water?</em> Añade siempre <strong>please</strong> al final. Para pedir la cuenta: <strong>Could I have the bill, please?</strong>"
        },
        "t3": {
          "heading": "Sustantivos contables e incontables",
          "body": "Algunas palabras de comida son <strong>contables</strong> — tienen forma singular y plural: <em>an apple / two apples, an egg / three eggs, a sandwich / two sandwiches.</em> Otras son <strong>incontables</strong> — no tienen plural y no se pueden usar con <em>a/an</em>: <em>milk, bread, water, butter, rice.</em> Con los sustantivos incontables usa <strong>some</strong> (en afirmativo) o <strong>any</strong> (en negativo/pregunta): <em>I'd like some milk. We don't have any bread. Do you have any coffee?</em>"
        }
      },
      "examples": {
        "e1": "Quisiera un café con leche, por favor.",
        "e2": "¿Me puede traer pan y mantequilla, por favor?",
        "e3": "Ella come una manzana todos los días.",
        "e4": "Necesitamos leche y dos huevos.",
        "e5": "La pasta es muy buena en este restaurante.",
        "e6": "¿Quieres un poco más de té?",
        "e7": "No como carne. Soy vegetariano.",
        "e8": "El pescado con papas fritas es un plato tradicional británico."
      },
      "flashcards": {
        "f1": "Pan",
        "f2": "Leche",
        "f3": "Café",
        "f4": "Té",
        "f5": "Huevo",
        "f6": "Pollo",
        "f7": "Verduras",
        "f8": "Quisiera…",
        "f9": "La cuenta, por favor",
        "f10": "Algo de (con incontables)"
      },
      "quiz": {
        "q1": "Milk es incontable — no puedes decir 'a milk' ni 'two milks'. Usa 'some milk'.",
        "q2": "'A coffee' significa una taza — coffee es contable al pedir una porción. 'The coffee' se refiere a uno concreto ya mencionado. 'An' solo va antes de sonidos vocálicos. 'Any' es para negativos y preguntas.",
        "q3": "El menú (la carta) enumera toda la comida y bebida disponible.",
        "q4": "Usa 'any' en negativos con sustantivos incontables: 'I don't have any bread.'",
        "q5": "'Would you like some more?' es un ofrecimiento, no una petición."
      }
    },
    "a1-day": {
      "title": "Rutinas diarias",
      "theory": {
        "t1": {
          "heading": "Presente simple para hábitos y rutinas",
          "body": "Usa el <strong>presente simple</strong> para cosas que haces con regularidad — cada día, cada semana, etc. <em>I wake up at 7. She goes to work by bus. He reads before bed.</em> El verbo cambia para <strong>he / she / it</strong>: añade <strong>-s</strong> o <strong>-es</strong>. Reglas: la mayoría de los verbos + <em>s</em>: <em>work → works, eat → eats.</em> Verbos terminados en -ch, -sh, -ss, -x, -o + <em>es</em>: <em>watch → watches, go → goes.</em> Irregulares: <em>have → has, be → is.</em>"
        },
        "t2": {
          "heading": "Adverbios de frecuencia",
          "body": "Los adverbios de frecuencia indican CON QUÉ FRECUENCIA ocurre algo: <strong>always (siempre, 100%), usually (normalmente, ≈80%), often (a menudo, ≈60%), sometimes (a veces, ≈40%), rarely/seldom (raramente, ≈10%), never (nunca, 0%).</strong> Colócalos <strong>antes del verbo principal</strong>: <em>I always eat breakfast. She never drinks coffee. He often goes to the gym.</em> Excepción — colócalos <strong>después del verbo 'be'</strong>: <em>He is always late. She is usually happy.</em>"
        },
        "t3": {
          "heading": "Expresiones de tiempo para rutinas",
          "body": "Expresiones de tiempo útiles: <strong>every day / week / morning / evening / Monday.</strong> Usa <strong>in</strong> con las partes del día: <em>in the morning, in the afternoon, in the evening.</em> Usa <strong>at</strong> con 'night' y las horas: <em>at night, at 8 o'clock.</em> Usa <strong>on</strong> con los días: <em>on Monday, on Fridays.</em> Usa <strong>from…to</strong> para un periodo: <em>from nine to five.</em>"
        }
      },
      "examples": {
        "e1": "Me despierto a las seis y media todas las mañanas.",
        "e2": "Ella siempre desayuna antes del trabajo.",
        "e3": "Él va al gimnasio tres veces por semana.",
        "e4": "Normalmente cenamos a las siete.",
        "e5": "Los niños nunca se acuestan tarde.",
        "e6": "Ella trabaja en una oficina de nueve a cinco.",
        "e7": "¿Bebes café por la mañana?",
        "e8": "A veces él lee un libro antes de dormir."
      },
      "flashcards": {
        "f1": "Despertarse",
        "f2": "Desayunar",
        "f3": "Ir al trabajo",
        "f4": "Volver a casa",
        "f5": "Cenar",
        "f6": "Acostarse / Irse a la cama",
        "f7": "Siempre",
        "f8": "A veces",
        "f9": "Nunca",
        "f10": "Cada día / Todos los días"
      },
      "quiz": {
        "q1": "Añade -es a 'go' para he/she/it: she goes.",
        "q2": "Con el verbo 'be', los adverbios de frecuencia van DESPUÉS: 'He is always late.'",
        "q3": "'He usually works from home' es correcta. 'Goes' y 'eat' tienen mala concordancia; 'is' debe ir antes de 'always'.",
        "q4": "Usa 'in' con las partes del día: in the morning, in the afternoon, in the evening.",
        "q5": "La tercera persona del singular (he/she/it) necesita -s: reads."
      }
    },
    "a1-town": {
      "title": "Lugares en la ciudad y preposiciones",
      "theory": {
        "t1": {
          "heading": "Lugares en la ciudad",
          "body": "Lugares clave: <strong>bank</strong> (banco), <strong>supermarket</strong> (supermercado), <strong>post office</strong> (oficina de correos), <strong>library</strong> (biblioteca), <strong>hospital</strong>, <strong>school</strong> (escuela), <strong>park</strong> (parque), <strong>cinema</strong> (cine), <strong>restaurant</strong> (restaurante), <strong>hotel</strong>, <strong>bus stop</strong> (parada de autobús), <strong>train station</strong> (estación de tren), <strong>pharmacy / chemist</strong> (farmacia), <strong>police station</strong> (comisaría), <strong>sports centre</strong> (polideportivo), <strong>town hall</strong> (ayuntamiento), <strong>museum</strong> (museo), <strong>café</strong> (cafetería). Nota sobre el inglés británico: <em>chemist</em> (= pharmacy), <em>cinema</em> (= movie theater en EE. UU.), <em>car park</em> (= parking lot en EE. UU.)."
        },
        "t2": {
          "heading": "Preposiciones de lugar",
          "body": "Memoriza estas: <strong>next to</strong> (al lado de) — the café is next to the bank. <strong>opposite</strong> (enfrente de) — the library is opposite the park. <strong>between</strong> (entre) — the shop is between the bank and the café. <strong>in front of</strong> (delante de) — the bus stop is in front of the cinema. <strong>behind</strong> (detrás de) — the car park is behind the hotel. <strong>near</strong> (cerca de) — the station is near the town centre. <strong>on the corner of</strong> (en la esquina de)."
        },
        "t3": {
          "heading": "Pedir y dar indicaciones",
          "body": "Para preguntar: <strong>Excuse me, where is the bank?</strong> / <strong>How do I get to the station?</strong> / <strong>Is there a pharmacy near here?</strong> Para dar indicaciones: <strong>Go straight on</strong> (sigue recto). <strong>Turn left / right</strong> (gira a la izquierda / derecha) (at the traffic lights = en el semáforo). <strong>Take the first / second left</strong> (toma la primera / segunda a la izquierda). <strong>It's on the left / right</strong> (está a la izquierda / derecha). <strong>It's about a five-minute walk</strong> (está a unos cinco minutos a pie)."
        }
      },
      "examples": {
        "e1": "El supermercado está al lado de la estación de tren.",
        "e2": "El banco está enfrente de la oficina de correos.",
        "e3": "Disculpe, ¿hay una farmacia cerca de aquí?",
        "e4": "Sigue recto y gira a la izquierda en el semáforo.",
        "e5": "La biblioteca está entre la escuela y el parque.",
        "e6": "El hotel está en la esquina de High Street y Park Road.",
        "e7": "El hospital está detrás del supermercado.",
        "e8": "El cine está a unos diez minutos a pie de aquí."
      },
      "flashcards": {
        "f1": "Supermercado",
        "f2": "Oficina de correos",
        "f3": "Biblioteca",
        "f4": "Farmacia",
        "f5": "Al lado de",
        "f6": "Enfrente de",
        "f7": "Entre",
        "f8": "Gira a la izquierda",
        "f9": "Sigue recto",
        "f10": "En la esquina"
      },
      "quiz": {
        "q1": "'Between' se usa cuando algo está en medio de dos cosas.",
        "q2": "'Where' pregunta por la ubicación.",
        "q3": "Una library (biblioteca) es donde tomas libros prestados gratis.",
        "q4": "'Opposite' significa justo enfrente de algo.",
        "q5": "'Excuse me, how do I get to…?' es la forma correcta y cortés de pedir indicaciones."
      }
    },
    "a2-past": {
      "title": "Hablar del pasado",
      "theory": {
        "t1": {
          "heading": "Pasado simple: verbos regulares",
          "body": "Añade <strong>-ed</strong> para formar el pasado simple de los verbos regulares: <em>work → worked, watch → watched, play → played.</em> Reglas de ortografía: los verbos terminados en <em>-e</em> solo añaden <em>-d</em>: <em>live → lived, dance → danced.</em> Los verbos terminados en vocal corta + consonante doblan la consonante: <em>stop → stopped, plan → planned.</em> Los verbos terminados en consonante + <em>-y</em> cambian a <em>-ied</em>: <em>study → studied, carry → carried.</em>"
        },
        "t2": {
          "heading": "Pasado simple: verbos irregulares",
          "body": "Muchos verbos comunes son irregulares — hay que memorizar la forma de pasado. Esenciales: <strong>go → went, come → came, see → saw, eat → ate, drink → drank, have → had, be → was/were, do → did, say → said, get → got, make → made, take → took, know → knew, think → thought, find → found, buy → bought, write → wrote, read → read (misma escritura, distinta pronunciación), tell → told, give → gave, feel → felt.</strong>"
        },
        "t3": {
          "heading": "Negativos y preguntas en pasado simple",
          "body": "Para los <strong>negativos</strong>: sujeto + <strong>didn't</strong> (did not) + infinitivo. <em>I didn't go. She didn't eat. They didn't know.</em> Para las <strong>preguntas de sí/no</strong>: <strong>Did</strong> + sujeto + infinitivo. <em>Did you go? Did she eat? Did they know?</em> Para las <strong>preguntas con wh-</strong>: palabra interrogativa + did + sujeto + infinitivo. <em>Where did you go? What did she eat?</em> IMPORTANTE: el verbo principal siempre queda en infinitivo (forma base) — NUNCA añadas -ed en preguntas o negativos."
        }
      },
      "examples": {
        "e1": "Ayer fui al cine con mis amigos.",
        "e2": "Ella trabajó en un restaurante cuando era más joven.",
        "e3": "No fuimos a la escuela el lunes pasado — era festivo.",
        "e4": "¿Viste el partido de fútbol anoche?",
        "e5": "Él hizo un pastel delicioso para la fiesta.",
        "e6": "Viví en Londres durante tres años.",
        "e7": "Ellos no sabían la respuesta a la pregunta.",
        "e8": "¿Cuándo llegaste a Inglaterra?"
      },
      "flashcards": {
        "f1": "ir → fui/fue",
        "f2": "venir → vine/vino",
        "f3": "ver → vi/vio",
        "f4": "tener → tuve/tuvo",
        "f5": "ser/estar → fui/era",
        "f6": "hacer → hice/hizo",
        "f7": "comprar → compré/compró",
        "f8": "Ayer",
        "f9": "La semana pasada",
        "f10": "negación en pasado"
      },
      "quiz": {
        "q1": "'Went' es el pasado simple irregular de 'go'.",
        "q2": "Negativo: didn't + verbo base (sin -ed). 'I didn't watch' es correcto.",
        "q3": "Las preguntas en pasado simple usan 'did': Did you enjoy…?",
        "q4": "Vocal corta + consonante → se dobla la consonante: stop → stopped.",
        "q5": "'Was' es el pasado de 'be' para I/he/she/it. 'Were' es para you/we/they — por eso 'we were' es correcto."
      }
    },
    "a2-shop": {
      "title": "Compras y dinero",
      "theory": {
        "t1": {
          "heading": "Vocabulario de compras",
          "body": "Palabras esenciales: <strong>price</strong> (precio), <strong>cost</strong> (costar), <strong>how much</strong> (cuánto), <strong>receipt</strong> (recibo), <strong>change</strong> (cambio/vuelta), <strong>sale / on sale</strong> (rebajas / en oferta), <strong>discount</strong> (descuento), <strong>size</strong> (talla, S/M/L/XL), <strong>try on</strong> (probarse ropa), <strong>fit</strong> (quedar bien de talla), <strong>checkout</strong> (caja), <strong>till / cash register</strong> (caja registradora), <strong>cash</strong> (efectivo), <strong>card payment</strong> (pago con tarjeta), <strong>refund</strong> (reembolso). Inglés británico: <em>till</em> = cash register, <em>shop</em> = store, <em>queue</em> = line (cola)."
        },
        "t2": {
          "heading": "Preguntar por el precio",
          "body": "Preguntas clave: <strong>How much is this?</strong> (singular) / <strong>How much are these?</strong> (plural) / <strong>How much does this cost?</strong> Respuestas: <em>It costs twelve pounds fifty. It's two pounds. They are three for five pounds.</em> Leer precios: £12.50 = twelve pounds fifty; £0.99 = ninety-nine pence / p. Nota: <em>pence</em> es el plural de <em>penny</em>."
        },
        "t3": {
          "heading": "Peticiones corteses en las tiendas",
          "body": "Para pedir probarte algo: <strong>Can I try this on?</strong> Para preguntar por tallas: <strong>Do you have this in a medium / larger / smaller size?</strong> Para buscar algo: <strong>I'm looking for…</strong> Para comprobar disponibilidad: <strong>Do you have…?</strong> Para pagar: <strong>Could I pay by card?</strong> / <strong>Do you accept contactless?</strong> Para un recibo: <strong>Could I have a receipt, please?</strong>"
        }
      },
      "examples": {
        "e1": "¿Cuánto cuesta esta chaqueta?",
        "e2": "Cuesta treinta y cinco libras con cincuenta.",
        "e3": "¿Tiene esto en talla mediana?",
        "e4": "¿Podría probarme estos pantalones?",
        "e5": "Estoy buscando un regalo de cumpleaños para mi hermana.",
        "e6": "Hoy hay un 20% de descuento en todos los zapatos.",
        "e7": "¿Puedo pagar con tarjeta o es solo en efectivo?",
        "e8": "El recibo está en la bolsa."
      },
      "flashcards": {
        "f1": "¿Cuánto cuesta esto?",
        "f2": "Descuento",
        "f3": "Rebajas / Oferta",
        "f4": "Talla",
        "f5": "Recibo",
        "f6": "Cambio / Vuelta",
        "f7": "Probarse",
        "f8": "Reembolso",
        "f9": "Efectivo",
        "f10": "Estoy buscando…"
      },
      "quiz": {
        "q1": "'How much is this jacket?' es la forma corta estándar y está completa. 'Does' por sí solo deja la frase incompleta — habría que añadir 'cost' al final: 'How much does this jacket cost?'",
        "q2": "Pedimos otra 'size' (talla) cuando la ropa no nos queda bien.",
        "q3": "Pagar con tarjeta es la alternativa a pagar en efectivo.",
        "q4": "Un descuento del 20% significa que el precio se reduce en un 20%.",
        "q5": "'I'm looking for something' significa que quieres encontrarlo o comprarlo."
      }
    },
    "a2-compare": {
      "title": "Comparar cosas",
      "theory": {
        "t1": {
          "heading": "Comparativos — bigger, more expensive",
          "body": "Para comparar dos cosas, los adjetivos cortos añaden <strong>-er + than</strong>: <em>tall → taller, old → older, cheap → cheaper</em>. Ortografía: <em>big → bigger</em> (doble consonante), <em>happy → happier</em> (-y → -ier). Los adjetivos largos (dos o más sílabas) usan <strong>more … than</strong>: <em>more expensive than, more interesting than</em>. Irregulares: <strong>good → better</strong> (mejor), <strong>bad → worse</strong> (peor). <em>Santiago is bigger than Valparaíso. This café is better than that one.</em> Nunca mezcles las dos formas: di <em>bigger</em>, no <em>more big</em>."
        },
        "t2": {
          "heading": "Superlativos — the biggest, the most expensive",
          "body": "Para comparar una cosa con todo un grupo, usa <strong>the + -est</strong> con adjetivos cortos (<em>the tallest, the cheapest, the biggest</em>) y <strong>the most + adjetivo</strong> con los largos (<em>the most expensive, the most beautiful</em>). Irregulares: <strong>the best</strong> (el mejor), <strong>the worst</strong> (el peor). A menudo añadimos <em>in</em> + un lugar o grupo: <em>It's the tallest building in South America. She's the best student in the class.</em> Recuerda la palabra <strong>the</strong> — es parte del superlativo."
        },
        "t3": {
          "heading": "Cuantificadores — much, many, a few, a little",
          "body": "<strong>Many</strong> va con sustantivos contables en plural; <strong>much</strong> va con sustantivos incontables, sobre todo en preguntas y negaciones: <em>How many friends?</em> (¿cuántos?) <em>How much money?</em> (¿cuánto?) <em>I don't have much time.</em> <strong>A lot of</strong> (mucho/muchos) funciona con ambos: <em>a lot of people, a lot of water</em>. Para cantidades pequeñas: <strong>a few</strong> + contable (<em>a few apples</em> = unas pocas), <strong>a little</strong> + incontable (<em>a little sugar</em> = un poco). <strong>Too many / too much</strong> = más de lo conveniente: <em>too many cars, too much noise</em>."
        }
      },
      "examples": {
        "e1": "Santiago es más grande que Valparaíso.",
        "e2": "Esta chaqueta es más cara que esa.",
        "e3": "Mi inglés es mejor que el año pasado.",
        "e4": "Este es el café más barato del barrio.",
        "e5": "Esa fue la película más interesante del año.",
        "e6": "¿Cuántas manzanas necesitamos? — Solo unas pocas.",
        "e7": "Este jugo tiene demasiada azúcar.",
        "e8": "No tengo mucho tiempo, pero tengo un poco de plata."
      },
      "flashcards": {
        "f1": "Adjetivo + -er + than: taller than",
        "f2": "more + adjetivo + than: more expensive than",
        "f3": "Mejor (comparativo de 'good')",
        "f4": "Peor (comparativo de 'bad')",
        "f5": "El/la mejor (superlativo de 'good')",
        "f6": "Con incontables: much money, much time",
        "f7": "Con contables en plural: many books",
        "f8": "Unos pocos (contable): a few friends",
        "f9": "Un poco (incontable): a little water",
        "f10": "Demasiado / demasiados (más de lo deseado)"
      },
      "quiz": {
        "q1": "Los adjetivos cortos añaden -er en el comparativo: bigger than. 'More big' es incorrecto, y 'the biggest' es un superlativo.",
        "q2": "'Good' es irregular: good → better → the best. El superlativo compara una cosa con todo un grupo.",
        "q3": "Los adjetivos largos forman el comparativo con 'more … than': more interesting than.",
        "q4": "'Water' es incontable, así que usa 'much'. 'Many' es solo para sustantivos contables.",
        "q5": "'Cars' es un sustantivo contable en plural, así que usa 'too many'. 'Too much' es para incontables."
      }
    },
    "a2-travel": {
      "title": "Viajes e indicaciones",
      "theory": {
        "t1": {
          "heading": "Vocabulario de transporte y viajes",
          "body": "Tipos de transporte: <strong>bus</strong> (autobús), <strong>train</strong> (tren), <strong>plane / flight</strong> (avión / vuelo), <strong>taxi / cab</strong>, <strong>underground / tube / metro</strong>, <strong>ferry</strong> (transbordador), <strong>tram</strong> (tranvía), <strong>car</strong> (auto), <strong>bicycle / bike</strong> (bicicleta). Lugares relacionados: <strong>airport</strong> (aeropuerto), <strong>bus stop</strong> (parada de autobús), <strong>train station</strong> (estación de tren), <strong>platform</strong> (andén), <strong>terminal</strong>, <strong>port</strong> (puerto), <strong>harbour</strong> (puerto). Verbos útiles: <em>catch a train/bus</em> (tomarlo a tiempo), <em>miss a train/bus</em> (perderlo por llegar tarde), <em>get on</em> (subir), <em>get off</em> (bajar), <em>change</em> (cambiar de línea/tren)."
        },
        "t2": {
          "heading": "Comprar boletos",
          "body": "Un boleto <strong>single</strong> (o one-way) = viaje solo en una dirección. Un boleto <strong>return</strong> = ida y vuelta. <strong>First class</strong> = más cómodo, más caro. <strong>Standard / second class</strong> = normal. Frases: <em>A single to Edinburgh, please. Two returns to Oxford, please. Which platform does the train leave from? Is this seat taken? Does this train stop at Bath?</em>"
        },
        "t3": {
          "heading": "Moverse en transporte público",
          "body": "Preguntar: <strong>Excuse me, how do I get to…?</strong> (¿cómo llego a…?) / <strong>Is it far?</strong> (¿está lejos?) / <strong>How long does it take?</strong> (¿cuánto se demora?) Indicaciones en transporte público: <strong>Take the number 5 bus</strong> (toma el autobús número 5). <strong>Get off at the third stop</strong> (bájate en la tercera parada). <strong>Change at the central station</strong> (haz transbordo en la estación central). <strong>Which platform does the train leave from?</strong> (¿de qué andén sale el tren?) <strong>Follow the signs for the metro</strong> (sigue las señales hacia el metro). <strong>You can't miss it</strong> (= es fácil de ver)."
        }
      },
      "examples": {
        "e1": "¿Podría decirme cómo llegar al aeropuerto?",
        "e2": "Un boleto de ida y vuelta a Edimburgo, por favor.",
        "e3": "¿De qué andén sale el tren a Londres?",
        "e4": "Disculpe, ¿es este el autobús correcto para el centro de la ciudad?",
        "e5": "¿Cuánto dura el viaje en tren?",
        "e6": "Bájate en la tercera parada y luego gira a la derecha.",
        "e7": "El vuelo a Londres sale a las 14:35 desde la puerta B7.",
        "e8": "Perdí el autobús y tuve que tomar un taxi."
      },
      "flashcards": {
        "f1": "Boleto de ida",
        "f2": "Boleto de ida y vuelta",
        "f3": "Andén",
        "f4": "Salida",
        "f5": "Llegada",
        "f6": "Subir(se)",
        "f7": "Bajar(se)",
        "f8": "¿Cuánto se tarda?",
        "f9": "¿Está lejos?",
        "f10": "Hacer transbordo"
      },
      "quiz": {
        "q1": "Un 'return ticket' cubre tanto el viaje de ida como el de vuelta.",
        "q2": "Los trenes salen de los andenes (platforms) en una estación.",
        "q3": "'Get off' significa bajarse de un autobús, tren o avión.",
        "q4": "'Miss' un autobús o tren significa que llegaste demasiado tarde para tomarlo.",
        "q5": "Departure = cuando algo sale; Arrival = cuando llega."
      }
    },
    "a2-health": {
      "title": "La salud y el cuerpo",
      "theory": {
        "t1": {
          "heading": "Partes del cuerpo",
          "body": "Cabeza y cara: <strong>head</strong> (cabeza), <strong>forehead</strong> (frente), <strong>eye(s)</strong> (ojo/s), <strong>ear(s)</strong> (oreja/s), <strong>nose</strong> (nariz), <strong>mouth</strong> (boca), <strong>teeth</strong> (dientes, sing. tooth), <strong>cheek</strong> (mejilla), <strong>chin</strong> (barbilla), <strong>neck</strong> (cuello). Parte superior: <strong>shoulder</strong> (hombro), <strong>arm</strong> (brazo), <strong>elbow</strong> (codo), <strong>wrist</strong> (muñeca), <strong>hand</strong> (mano), <strong>finger</strong> (dedo), <strong>thumb</strong> (pulgar), <strong>chest</strong> (pecho), <strong>back</strong> (espalda), <strong>stomach</strong> (estómago). Parte inferior: <strong>hip</strong> (cadera), <strong>leg</strong> (pierna), <strong>knee</strong> (rodilla), <strong>ankle</strong> (tobillo), <strong>foot</strong> (pie, pl. feet), <strong>toe</strong> (dedo del pie). Órganos internos: <em>heart (corazón), lungs (pulmones), brain (cerebro), stomach.</em>"
        },
        "t2": {
          "heading": "Describir síntomas",
          "body": "Síntomas comunes: <strong>I have a headache</strong> (dolor de cabeza) <strong>/ stomach ache</strong> (de estómago) <strong>/ backache</strong> (de espalda) <strong>/ toothache</strong> (de muelas). <strong>I have a sore throat</strong> (dolor de garganta) <strong>/ sore eyes.</strong> <strong>I feel sick / nauseous</strong> (tengo náuseas). <strong>I have a cold</strong> (resfriado) <strong>/ the flu</strong> (gripe) <strong>/ a fever</strong> (fiebre) <strong>/ a cough</strong> (tos) <strong>/ a rash</strong> (sarpullido). <strong>I've injured / hurt / twisted my ankle</strong> (me he torcido el tobillo). <strong>I can't sleep.</strong> <strong>I feel dizzy</strong> (mareado) <strong>/ tired / weak.</strong> Nota: <em>a cold</em> pero <em>the flu</em> (con 'the')."
        },
        "t3": {
          "heading": "En el médico",
          "body": "El médico puede preguntar: <strong>What's the matter?</strong> (¿qué le pasa?) <strong>/ What seems to be the problem? / Where does it hurt?</strong> (¿dónde le duele?) <strong>/ How long have you had this?</strong> (¿desde cuándo?) Puedes responder: <strong>I've had it since yesterday / since Monday. It started three days ago. It hurts when I walk / breathe / swallow</strong> (me duele al andar / respirar / tragar). <strong>I'm allergic to penicillin.</strong> El médico podría decir: <strong>Take these tablets twice a day</strong> (tome estas pastillas dos veces al día). <strong>Rest and drink plenty of fluids. Come back if it gets worse.</strong> Nota gramatical: para decir cuánto tiempo lleva un problema, el inglés usa el <strong>presente perfecto</strong>: <strong>have/has + participio pasado</strong>. Usa <strong>for</strong> con una duración y <strong>since</strong> con un punto de inicio: <em>I've had this pain for two days. I've had it since Monday.</em> Estudiarás este tiempo con más detalle en B1."
        }
      },
      "examples": {
        "e1": "Tengo dolor de cabeza y dolor de garganta.",
        "e2": "Me ha dolido la espalda durante tres días.",
        "e3": "Ella fue al médico porque tenía fiebre alta.",
        "e4": "Me torcí el tobillo jugando al fútbol.",
        "e5": "¿Desde cuándo tienes esta tos?",
        "e6": "Soy alérgico a la penicilina, así que necesito otro medicamento.",
        "e7": "Tome estas pastillas dos veces al día después de las comidas.",
        "e8": "No me siento bien. Creo que tengo gripe."
      },
      "flashcards": {
        "f1": "Dolor de cabeza",
        "f2": "Dolor de garganta",
        "f3": "Fiebre",
        "f4": "Tos",
        "f5": "Dolor de estómago",
        "f6": "Tengo náuseas",
        "f7": "Alérgico a",
        "f8": "Pastilla / Comprimido",
        "f9": "Dos veces al día",
        "f10": "¿Qué le pasa?"
      },
      "quiz": {
        "q1": "A sore throat (dolor de garganta) es el síntoma cuando duele al tragar.",
        "q2": "Los médicos preguntan 'Where does it hurt?' para diagnosticar a un paciente.",
        "q3": "'For' + un periodo de tiempo indica cuánto tiempo lleva ocurriendo algo.",
        "q4": "'Twice a day' significa dos veces cada día.",
        "q5": "Una alergia provoca una reacción física negativa (sarpullido, problemas respiratorios, etc.)."
      }
    },
    "a2-modals": {
      "title": "Can, must, should",
      "theory": {
        "t1": {
          "heading": "Can, can't y could",
          "body": "<strong>Can</strong> expresa habilidad (<em>I can swim</em> = sé nadar) y permiso (<em>Can I open the window?</em> = ¿puedo abrir la ventana?). Negativo: <strong>can't</strong> — <em>I can't drive.</em> <strong>Could</strong> es el pasado de <em>can</em> (<em>I could read when I was five</em>) y también hace las peticiones más corteses: <em>Could you help me, please?</em> es más suave que <em>Can you help me?</em> Los verbos modales nunca cambian de forma y nunca van seguidos de <em>to</em>: di <em>I can swim</em>, no <em>I can to swim</em>."
        },
        "t2": {
          "heading": "Must, have to, mustn't, don't have to",
          "body": "<strong>Must</strong> y <strong>have to</strong> expresan obligación: <em>You must wear a seatbelt</em> (debes usar el cinturón). <em>I have to work tomorrow</em> (tengo que trabajar mañana). Cuidado con los negativos — ¡significan cosas muy distintas! <strong>Mustn't</strong> = prohibición, NO está permitido: <em>You mustn't smoke here.</em> <strong>Don't have to</strong> = sin obligación, no es necesario (pero puedes si quieres): <em>You don't have to come — it's optional.</em> Confundir estos dos es uno de los errores más comunes en este nivel."
        },
        "t3": {
          "heading": "Should para consejos, might para posibilidad",
          "body": "<strong>Should / shouldn't</strong> da consejos: <em>You should drink more water</em> (deberías tomar más agua). <em>You shouldn't go to bed so late.</em> Es más suave que <em>must</em> — una recomendación, no una obligación. <strong>Might</strong> expresa posibilidad — quizás sí, quizás no: <em>It might rain later</em> (puede que llueva más tarde). <em>She might come to the party.</em> Como todos los modales, van con el verbo base sin <em>to</em>: <em>You should rest</em>, no <em>You should to rest</em>."
        }
      },
      "examples": {
        "e1": "Sé nadar, pero no sé andar en bicicleta.",
        "e2": "¿Podrías abrir la ventana, por favor?",
        "e3": "¿Puedo usar tu teléfono? — Sí, claro.",
        "e4": "Debes usar el cinturón de seguridad en el auto.",
        "e5": "Está prohibido fumar en el hospital.",
        "e6": "No tienes que venir mañana — es feriado.",
        "e7": "Deberías tomar más agua y dormir más.",
        "e8": "Lleva paraguas — puede que llueva más tarde."
      },
      "flashcards": {
        "f1": "Habilidad o permiso: I can swim / Can I…?",
        "f2": "No poder: I can't drive",
        "f3": "Es más cortés que 'can': Could you help me?",
        "f4": "Obligación fuerte: You must stop",
        "f5": "Prohibición: está prohibido",
        "f6": "No es obligatorio (puedes elegir)",
        "f7": "Tener que: I have to work",
        "f8": "Consejo: You should rest",
        "f9": "No deberías (consejo negativo)",
        "f10": "Posibilidad: It might rain"
      },
      "quiz": {
        "q1": "'Mustn't' = prohibición, no está permitido. 'Don't have to' significa que no hay obligación — un significado muy distinto.",
        "q2": "'Don't have to' = no es necesario. 'Mustn't' significaría que está prohibido venir.",
        "q3": "'Could you…, please?' es la forma cortés de pedir algo. Las otras opciones son órdenes, no peticiones.",
        "q4": "'Should' da un consejo. Los verbos modales nunca van seguidos de 'to' — 'must to', 'might to' y 'can to' siempre son incorrectos.",
        "q5": "'Might' expresa posibilidad — quizás llueva, quizás no. 'Must' y 'should' no expresan posibilidad aquí."
      }
    },
    "a2-work": {
      "title": "El trabajo y las profesiones",
      "theory": {
        "t1": {
          "heading": "Vocabulario de profesiones",
          "body": "Profesiones comunes: <strong>teacher</strong> (profesor), <strong>doctor</strong> (médico), <strong>nurse</strong> (enfermero), <strong>engineer</strong> (ingeniero), <strong>lawyer</strong> (abogado), <strong>architect</strong> (arquitecto), <strong>journalist</strong> (periodista), <strong>chef / cook</strong> (cocinero), <strong>driver</strong> (conductor), <strong>manager</strong> (gerente), <strong>receptionist</strong> (recepcionista), <strong>accountant</strong> (contador), <strong>programmer / developer</strong> (programador), <strong>salesperson</strong> (vendedor), <strong>cleaner</strong> (limpiador), <strong>plumber</strong> (plomero), <strong>electrician</strong> (electricista), <strong>designer</strong> (diseñador), <strong>pilot</strong> (piloto), <strong>police officer</strong> (policía). Sectores: <em>healthcare (sanidad), education, IT, finance, retail (comercio), construction, media, hospitality (hostelería).</em>"
        },
        "t2": {
          "heading": "Hablar del trabajo",
          "body": "Preguntar por el trabajo: <strong>What do you do (for a living)?</strong> (¿a qué te dedicas?) Responder: <strong>I work as a nurse. / I'm a teacher. / I work for Google. / I work in IT / finance / education.</strong> Otras frases útiles: <strong>I'm self-employed</strong> (soy autónomo), <strong>I'm freelance</strong> (trabajo por cuenta propia), <strong>I'm unemployed / between jobs</strong> (estoy desempleado / entre trabajos), <strong>I'm retired</strong> (estoy jubilado), <strong>I work part-time / full-time</strong> (a tiempo parcial / completo)."
        },
        "t3": {
          "heading": "Frases del lugar de trabajo",
          "body": "Frases comunes: <strong>I have a meeting at ten</strong> (tengo una reunión a las diez). <strong>I'm on a deadline</strong> (tengo una fecha límite). <strong>I work from home / remotely</strong> (trabajo desde casa / en remoto). <strong>I work shifts</strong> (trabajo por turnos). <strong>I got a promotion</strong> (me ascendieron). <strong>I applied for a job</strong> (solicité un trabajo). <strong>I had an interview</strong> (tuve una entrevista). <strong>I was offered the job / I got the job</strong> (me ofrecieron / conseguí el trabajo)."
        }
      },
      "examples": {
        "e1": "¿A qué te dedicas? — Trabajo como enfermero.",
        "e2": "Ella es ingeniera en una gran empresa de tecnología.",
        "e3": "Trabajo desde casa tres días a la semana.",
        "e4": "Él solicitó un trabajo como profesor el mes pasado.",
        "e5": "Mi hermana es autónoma. Lleva su propia panadería.",
        "e6": "Me ascendieron el año pasado y ahora dirijo un equipo de diez personas.",
        "e7": "Ella trabaja muchas horas como médica, a menudo doce horas al día.",
        "e8": "Estoy entre trabajos ahora mismo, pero tengo una entrevista mañana."
      },
      "flashcards": {
        "f1": "Trabajo como…",
        "f2": "Trabajo para…",
        "f3": "Autónomo",
        "f4": "Ascenso",
        "f5": "Solicitar un trabajo",
        "f6": "Entrevista",
        "f7": "A tiempo completo",
        "f8": "A tiempo parcial",
        "f9": "Fecha límite",
        "f10": "Trabajar desde casa"
      },
      "quiz": {
        "q1": "'Work as' describe tu puesto o título laboral.",
        "q2": "Las personas self-employed dirigen su propio negocio o trabajan de forma independiente.",
        "q3": "Un 'promotion' (ascenso) es cuando pasas a un puesto mejor y más alto en la misma empresa.",
        "q4": "'What do you do for a living?' pregunta por tu profesión.",
        "q5": "'On a deadline' significa que tienes un plazo para terminar algo."
      }
    },
    "a2-plans": {
      "title": "Hacer planes",
      "theory": {
        "t1": {
          "heading": "Going To — para planes ya decididos",
          "body": "Usa <strong>be going to + infinitivo</strong> para planes e intenciones que ya has decidido. <em>I'm going to visit my parents next weekend. She's going to start a new job in September. They're going to move to a bigger flat.</em> Estructura: <strong>I am / He is / They are + going to + verbo.</strong> Negativos: <em>I'm not going to go. She isn't going to come.</em>"
        },
        "t2": {
          "heading": "Will — para decisiones espontáneas y predicciones",
          "body": "Usa <strong>will + infinitivo</strong> para decisiones tomadas en el momento de hablar (no planeadas): <em>It's very hot. I'll open a window. Don't worry, I'll help you.</em> Usa <em>will</em> también para predicciones sobre el futuro (especialmente con think, probably, expect): <em>I think it will rain tomorrow. Prices will probably rise.</em> Estructura: <strong>sujeto + will + infinitivo.</strong> Contracción: <em>I'll, you'll, he'll, she'll, it'll, we'll, they'll.</em>"
        },
        "t3": {
          "heading": "Presente continuo para planes fijos futuros",
          "body": "Usa el <strong>presente continuo (am/is/are + -ing)</strong> para planes fijos en el futuro — citas, reservas, reuniones ya organizadas: <em>I'm meeting John on Tuesday. She's flying to Rome tomorrow. We're having dinner with the manager on Friday.</em> Es parecido a 'going to' pero enfatiza que el plan está confirmado. Expresiones de tiempo futuro: <em>tomorrow, next week/month/year, in two weeks, soon, this weekend, on Saturday.</em>"
        }
      },
      "examples": {
        "e1": "Vamos a visitar a mis padres el próximo fin de semana.",
        "e2": "Voy a empezar un nuevo trabajo en septiembre.",
        "e3": "Hace mucho calor aquí. Abriré una ventana.",
        "e4": "No te preocupes, te ayudaré con la presentación.",
        "e5": "¿Qué vas a hacer para tu cumpleaños?",
        "e6": "Ella se reúne con su jefe mañana a las diez.",
        "e7": "Creo que va a ser un examen difícil.",
        "e8": "¿Estarás en la fiesta el sábado?"
      },
      "flashcards": {
        "f1": "Para un plan ya decidido o una predicción basada en evidencia",
        "f2": "Para una decisión espontánea o una predicción de opinión",
        "f3": "Me reúno con… (cita)",
        "f4": "La próxima semana",
        "f5": "Mañana",
        "f6": "Pronto",
        "f7": "Este fin de semana",
        "f8": "Creo que… (+ futuro)",
        "f9": "Plan / intención",
        "f10": "Cita / Acuerdo"
      },
      "quiz": {
        "q1": "'Going to' se usa para planes y decisiones ya tomadas.",
        "q2": "'Will' se usa para decisiones espontáneas tomadas en el momento de hablar.",
        "q3": "El presente continuo (is meeting) muestra un evento futuro confirmado y acordado.",
        "q4": "'I'm going to go' muestra una intención planeada de antemano.",
        "q5": "Los ofrecimientos y decisiones espontáneas usan 'will'."
      }
    },
    "b1-perfect": {
      "title": "Presente perfecto y hábitos pasados",
      "theory": {
        "t1": {
          "heading": "Presente perfecto — forma, for y since",
          "body": "El <strong>presente perfecto</strong> = <strong>have/has + participio pasado</strong>: <em>I have finished. She has arrived.</em> Úsalo para acciones que empezaron en el pasado y continúan ahora, con <strong>for</strong> + un período y <strong>since</strong> + un punto de inicio: <em>I have lived here for ten years</em> (durante diez años). <em>She has worked there since 2020</em> (desde 2020). Aprende los participios irregulares comunes: <em>be → been, go → gone, see → seen, do → done, make → made, take → taken, eat → eaten, write → written</em>."
        },
        "t2": {
          "heading": "Just, already, yet — y cuándo usar el pasado simple",
          "body": "<strong>Just</strong> = hace muy poco tiempo: <em>I have just finished lunch</em> (recién terminé de almorzar). <strong>Already</strong> = antes de lo esperado: <em>She has already left</em> (ya se fue). <strong>Yet</strong> va al final de preguntas y negaciones: <em>Have you eaten yet? I haven't seen it yet</em> (todavía no). Contraste importante: con un <strong>marcador de tiempo terminado</strong> (<em>yesterday, last week, in 2019, two hours ago</em>) usa siempre el <strong>pasado simple</strong>: <em>I saw her yesterday</em> — nunca <em>I have seen her yesterday</em>."
        },
        "t3": {
          "heading": "Used to — hábitos pasados",
          "body": "<strong>Used to + infinitivo</strong> describe hábitos o estados pasados que ya no son verdad: <em>I used to smoke</em> (antes fumaba). <em>We used to live in Valparaíso. She used to hate fish, but now she loves it.</em> Negativo: <strong>didn't use to</strong> (ojo con la ortografía — sin -d final): <em>I didn't use to like coffee.</em> Pregunta: <em>Did you use to play football?</em> Para hábitos presentes, usa el presente simple: <em>I usually walk to work</em> — 'use to' no existe en el presente."
        }
      },
      "examples": {
        "e1": "He vivido en Santiago durante diez años.",
        "e2": "Ella trabaja en el hospital desde 2020.",
        "e3": "Recién terminé mi tarea.",
        "e4": "¿Ya compraste los boletos? — Sí, ya lo hice.",
        "e5": "Todavía no hemos visto esa película.",
        "e6": "Visité Valparaíso el verano pasado.",
        "e7": "Antes fumaba, pero lo dejé hace dos años.",
        "e8": "Antes no le gustaba el café, pero ahora lo toma todos los días."
      },
      "flashcards": {
        "f1": "have/has + participio pasado",
        "f2": "Con un período: for ten years",
        "f3": "Con un punto de inicio: since 2020",
        "f4": "Recién / acabar de: I have just arrived",
        "f5": "Ya (antes de lo esperado)",
        "f6": "Todavía / ya (en negaciones y preguntas)",
        "f7": "gone (go, went, gone)",
        "f8": "seen (see, saw, seen)",
        "f9": "Hábitos pasados que ya no existen: I used to smoke",
        "f10": "didn't use to (sin -d final)"
      },
      "quiz": {
        "q1": "'Since' marca el punto de inicio (since 2019); 'for' se usa con un período (for five years).",
        "q2": "'Last year' es un marcador de tiempo terminado, así que usa el pasado simple: went. El presente perfecto no puede usarse con tiempos terminados.",
        "q3": "'Yet' va al final de preguntas y negaciones: Have you finished yet?",
        "q4": "'Used to + infinitivo' describe un hábito pasado que terminó. En oraciones afirmativas la forma es 'used to', con -d final.",
        "q5": "Write es irregular: write, wrote, written. El presente perfecto es 'have written'."
      }
    },
    "b1-structures": {
      "title": "Construir mejores oraciones",
      "theory": {
        "t1": {
          "heading": "Oraciones de relativo — who, which, that",
          "body": "Las oraciones de relativo unen dos ideas en una sola oración. Usa <strong>who</strong> para personas, <strong>which</strong> para cosas y <strong>that</strong> para ambas: <em>The woman who lives next door is a nurse</em> (la mujer que vive al lado). <em>This is the book which/that changed my life.</em> Cuando el pronombre relativo es el <strong>objeto</strong> de la cláusula, puedes omitirlo: <em>The film (that) we watched was brilliant.</em> No puedes omitirlo cuando es el sujeto: <em>The man who called was my boss.</em>"
        },
        "t2": {
          "heading": "La voz pasiva — is made, was built",
          "body": "Forma la <strong>voz pasiva</strong> con <strong>be + participio pasado</strong>. Presente simple: <em>Wine is made in Chile</em> (el vino se produce en Chile). <em>These phones are produced in Asia.</em> Pasado simple: <em>The bridge was built in 1912</em> (el puente fue construido en 1912). <em>The letters were sent on Monday.</em> Usa la pasiva cuando quien hace la acción es desconocido o poco importante — la acción importa más que el agente. Para mencionar al agente, añade <strong>by</strong>: <em>The novel was written by a Chilean author.</em>"
        },
        "t3": {
          "heading": "¿Gerundio o infinitivo?",
          "body": "Algunos verbos van seguidos de la <strong>forma -ing (gerundio)</strong>: <strong>enjoy, finish, mind</strong> — <em>I enjoy reading</em> (disfruto leer). <em>She finished eating. Do you mind waiting?</em> Otros llevan el <strong>infinitivo con to</strong>: <strong>want, decide, hope</strong> — <em>I want to travel. We decided to stay. I hope to see you soon.</em> Algunos verbos aceptan ambos casi sin cambio de significado: <strong>like, love, start</strong> — <em>I like cooking / I like to cook.</em> Cuando aprendas un verbo nuevo, aprende también su patrón."
        }
      },
      "examples": {
        "e1": "La mujer que vive al lado es enfermera.",
        "e2": "Este es el libro que cambió mi vida.",
        "e3": "La película que vimos anoche estuvo genial.",
        "e4": "El vino se produce en el valle del Maipo.",
        "e5": "Este puente fue construido en 1912.",
        "e6": "Disfruto caminar por la playa en Valparaíso.",
        "e7": "Ella decidió estudiar inglés en el extranjero.",
        "e8": "¿Te molesta esperar unos minutos?"
      },
      "flashcards": {
        "f1": "Para personas: the man who called",
        "f2": "Para cosas: the car which broke down",
        "f3": "Cuando es objeto: the book (that) I read",
        "f4": "be + participio pasado: is made / was built",
        "f5": "Cuando el agente no importa o no se conoce",
        "f6": "Introduce al agente: written by García",
        "f7": "Gerundio (-ing): I enjoy reading",
        "f8": "Infinitivo con to: I want to travel",
        "f9": "Gerundio (-ing): She finished eating",
        "f10": "Infinitivo con to: We decided to stay"
      },
      "quiz": {
        "q1": "'Who' es el pronombre relativo para personas. 'Which' es para cosas, y 'what' y 'where' no son pronombres relativos aquí.",
        "q2": "Pasiva en presente simple = is/are + participio pasado: is made. 'Makes' e 'is making' son formas activas.",
        "q3": "Pasiva en pasado simple = was/were + participio pasado: was built. El museo no construyó nada — recibió la acción.",
        "q4": "'Enjoy' siempre va seguido de la forma -ing: enjoy listening.",
        "q5": "'Decide' va seguido del infinitivo con to: decided to look for."
      }
    },
    "b1-opinion": {
      "title": "Dar opiniones y mostrar acuerdo",
      "theory": {
        "t1": {
          "heading": "Frases para expresar tu opinión",
          "body": "Usa estas frases para introducir una opinión personal (no un hecho): <strong>In my opinion… / I think / believe / feel that… / As far as I'm concerned… / From my point of view… / It seems to me that… / Personally, I think…</strong> Indican que lo que sigue es tu perspectiva, no una verdad objetiva. Usarlas hace que tu inglés suene más natural y cortés, especialmente en debates y redacciones."
        },
        "t2": {
          "heading": "Estar de acuerdo y en desacuerdo con cortesía",
          "body": "<strong>Mostrar acuerdo:</strong> <em>I agree (with you). That's a good point. Absolutely. Exactly. I couldn't agree more. You're absolutely right. That's true.</em> <strong>Acuerdo/desacuerdo parcial:</strong> <em>I see your point, but… / That's true, but… / I agree to some extent, but…</em> <strong>Mostrar desacuerdo con cortesía:</strong> <em>I'm not sure about that. / I disagree. / Actually, I think… / With respect, I think… / I see it differently.</em> Nota: en inglés, la contradicción directa suele suavizarse."
        },
        "t3": {
          "heading": "Pedir la opinión de los demás",
          "body": "Para incluir a alguien en un debate: <strong>What do you think about…? / What's your view on…? / How do you feel about…? / Do you agree that…? / What's your opinion on…? / Would you say that…?</strong> En debates más formales: <strong>What are your thoughts on this? / I'd be interested to hear your view.</strong> Pedir opiniones equilibra la conversación y muestra respeto por los demás."
        }
      },
      "examples": {
        "e1": "En mi opinión, aprender un idioma requiere paciencia y práctica.",
        "e2": "Creo que las redes sociales tienen tanto ventajas como desventajas.",
        "e3": "Entiendo tu punto, pero creo que necesitamos más pruebas antes de decidir.",
        "e4": "¿Cuál es tu opinión sobre trabajar desde casa a tiempo completo?",
        "e5": "Estoy completamente de acuerdo — proteger el medioambiente es nuestro mayor reto.",
        "e6": "En lo que a mí respecta, el nuevo plan necesita mucha más reflexión.",
        "e7": "Es una perspectiva interesante, pero ¿has considerado los costos?",
        "e8": "Personalmente, creo que deberíamos invertir más en transporte público."
      },
      "flashcards": {
        "f1": "En mi opinión…",
        "f2": "Creo que…",
        "f3": "Estoy de acuerdo",
        "f4": "No estoy de acuerdo",
        "f5": "Es un buen argumento",
        "f6": "Entiendo tu punto, pero…",
        "f7": "Estoy totalmente de acuerdo",
        "f8": "¿Cuál es tu opinión sobre…?",
        "f9": "Desde mi punto de vista…",
        "f10": "Personalmente, creo que…"
      },
      "quiz": {
        "q1": "'In my opinion' introduce una opinión personal, no un hecho.",
        "q2": "'I couldn't agree more' es una expresión que significa 'estoy totalmente de acuerdo'.",
        "q3": "Esta frase reconoce la opinión del otro mientras introduce una diferente.",
        "q4": "'What's your view on…?' es una pregunta que invita a alguien a dar su opinión.",
        "q5": "'As far as I'm concerned' introduce una perspectiva u opinión personal."
      }
    },
    "b1-story": {
      "title": "Contar historias (tiempos narrativos)",
      "theory": {
        "t1": {
          "heading": "Pasado simple — eventos principales",
          "body": "El <strong>pasado simple</strong> cuenta los eventos principales de una historia en orden. Hace avanzar la narración. <em>She walked into the room. She saw a letter on the table. She picked it up and opened it.</em> Cada evento sigue al anterior. Es la 'columna vertebral' del relato. Usa conectores de tiempo para enlazar eventos: <em>first, then, after that, next, finally, suddenly, immediately, meanwhile</em> (mientras tanto = al mismo tiempo, en otro lugar). Tres conectores más enriquecen tus historias: <strong>because</strong> da una razón (<em>She left because she was tired.</em> = porque); <strong>although</strong> introduce un contraste dentro de una misma oración (<em>Although it was late, we kept walking.</em> = aunque); <strong>however</strong> contrasta con la oración anterior (<em>It was raining. However, we went out.</em> = sin embargo)."
        },
        "t2": {
          "heading": "Pasado continuo — fondo y acciones simultáneas",
          "body": "El <strong>pasado continuo</strong> (was/were + -ing) describe lo que ocurría como fondo cuando sucedieron los eventos principales. <em>It was raining when she arrived. Everyone was talking and laughing. The sun was shining over the city.</em> Úsalo también para dos acciones que ocurren al mismo tiempo: <em>While she was cooking, he was reading.</em> El pasado continuo ambienta la escena — por sí solo no hace avanzar la historia."
        },
        "t3": {
          "heading": "Pasado perfecto — eventos anteriores a la historia",
          "body": "El <strong>pasado perfecto</strong> (had + participio pasado) muestra que algo ocurrió <em>antes</em> que los eventos principales del pasado. <em>When he arrived, the show had already started.</em> (= El espectáculo empezó primero, luego él llegó.) <em>She had never visited London before.</em> <em>They had waited for an hour when the train finally came.</em> Úsalo para dejar clara la secuencia de eventos y dar profundidad a tu historia."
        }
      },
      "examples": {
        "e1": "Iba caminando a casa cuando de repente oí un ruido fuerte.",
        "e2": "Todos estaban cenando cuando se apagaron las luces.",
        "e3": "Para cuando llegamos, el tren ya se había ido.",
        "e4": "Ella nunca había visitado Londres antes, así que todo era nuevo para ella.",
        "e5": "Los niños jugaban en el jardín cuando empezó a llover.",
        "e6": "Abrió la puerta y descubrió que alguien había dejado un paquete fuera.",
        "e7": "Mientras esperaba el autobús, se encontró con un viejo amigo.",
        "e8": "Era una mañana preciosa. Los pájaros cantaban y el sol salía sobre las colinas."
      },
      "flashcards": {
        "f1": "Pasado continuo: was/were + -ing",
        "f2": "Pasado perfecto: had + participio",
        "f3": "Mientras… (dos acciones a la vez)",
        "f4": "Cuando… (fondo + evento)",
        "f5": "De repente",
        "f6": "Para cuando… (algo ya había pasado)",
        "f7": "Ya había…",
        "f8": "Mientras tanto",
        "f9": "Ella nunca había…",
        "f10": "Estaban + gerundio (fondo)"
      },
      "quiz": {
        "q1": "Pasado continuo (was reading) = acción de fondo interrumpida por el teléfono.",
        "q2": "Pasado perfecto (had left) muestra que la acción se completó antes de mi llegada.",
        "q3": "Pasado continuo = was/were + verbo en -ing.",
        "q4": "Pasado continuo (was playing) describe el ambiente de fondo.",
        "q5": "Pasado perfecto (had gone) muestra que esta acción se completó antes que otra acción pasada."
      }
    },
    "b1-if": {
      "title": "Hipótesis y condicionales",
      "theory": {
        "t1": {
          "heading": "Condicional cero — hechos y verdades generales",
          "body": "Estructura: <strong>If + presente simple, presente simple.</strong> Se usa para hechos, verdades científicas y cosas que siempre son ciertas: <em>If you heat water to 100°C, it boils. If I eat too much sugar, I get a headache. If it rains, the ground gets wet.</em> También puedes usar <em>when</em> en lugar de <em>if</em> con el mismo sentido. El resultado es seguro — no solo posible."
        },
        "t2": {
          "heading": "Primer condicional — posibilidad real futura",
          "body": "Estructura: <strong>If + presente simple, will + infinitivo.</strong> Se usa para situaciones reales y posibles en el futuro: <em>If it rains tomorrow, I will stay at home. If you study hard, you will pass the exam. If she calls, I'll tell her.</em> La situación es realmente posible. Puedes invertir las cláusulas: <em>I'll stay at home if it rains.</em> (Sin coma cuando la cláusula con 'if' va en segundo lugar.)"
        },
        "t3": {
          "heading": "Segundo condicional — situaciones imaginarias o improbables",
          "body": "Estructura: <strong>If + pasado simple, would + infinitivo.</strong> Se usa para situaciones imaginarias, hipotéticas o improbables AHORA o en el futuro: <em>If I had more time, I would travel more. If I were you, I would apply for the job. If she won the lottery, she would buy a house.</em> Nota especial: usa <strong>were</strong> (no <em>was</em>) después de <em>I</em> en la escritura formal: <em>If I were a doctor…</em> Esto se llama 'subjuntivo'. Otras palabras condicionales útiles: <strong>unless</strong> significa 'si no…': <em>You'll miss the train unless you hurry.</em> (= si no te apuras). <strong>Provided that</strong> y <strong>as long as</strong> significan 'solo si se cumple esta condición': <em>You can borrow my car provided that you drive carefully. We'll eat outside as long as it doesn't rain.</em>"
        }
      },
      "examples": {
        "e1": "Si tuviera más tiempo, viajaría por todo el mundo.",
        "e2": "Si estudias todos los días, mejorarás tu inglés.",
        "e3": "Si el agua baja de 0°C, se congela.",
        "e4": "Compraría una casa en el campo si me tocara la lotería.",
        "e5": "Si calientas la sopa, estará lista en cinco minutos.",
        "e6": "Si fuera médico, trabajaría en una organización sanitaria internacional.",
        "e7": "Perderás el tren si no te das prisa.",
        "e8": "¿Qué harías si pudieras vivir en cualquier lugar del mundo?"
      },
      "flashcards": {
        "f1": "If + presente → presente (hechos)",
        "f2": "If + presente → will (posibilidad real)",
        "f3": "If + pasado → would (hipotético)",
        "f4": "Yo… (condicional, hipotético)",
        "f5": "Si yo fuera tú…",
        "f6": "A menos que (= if … not)",
        "f7": "Siempre que / Con tal de que",
        "f8": "Mientras / Siempre que",
        "f9": "Hipotético / Imaginado",
        "f10": "Cláusula de resultado"
      },
      "quiz": {
        "q1": "Primer condicional: If + presente simple. 'If it rains' = posibilidad real.",
        "q2": "Segundo condicional: If + pasado simple. 'If I had a million pounds' = imaginario.",
        "q3": "El condicional cero expresa un hecho: mezclar colores siempre da el mismo resultado.",
        "q4": "Segundo condicional: If + pasado simple. 'If I had more free time' (pero no lo tengo).",
        "q5": "Segundo condicional = situaciones hipotéticas/imaginarias en el presente o el futuro."
      }
    },
    "b1-news": {
      "title": "Noticias, medios y estilo indirecto",
      "theory": {
        "t1": {
          "heading": "Vocabulario de noticias y medios",
          "body": "Tipos de medios: <strong>newspaper</strong> (periódico), <strong>magazine</strong> (revista), <strong>online news</strong> (noticias en línea), <strong>TV / broadcast news</strong>, <strong>podcast</strong>, <strong>social media</strong> (redes sociales), <strong>radio</strong>. Personas: <strong>journalist</strong> (periodista), <strong>reporter</strong>, <strong>editor</strong> (redactor jefe), <strong>correspondent</strong> (corresponsal), <strong>presenter / anchor</strong> (presentador). Tipos de noticia: <strong>headline</strong> (titular), <strong>article</strong> (artículo), <strong>report</strong> (reportaje), <strong>editorial</strong> (artículo de opinión), <strong>breaking news</strong> (noticia de última hora), <strong>interview, feature.</strong> Para citar fuentes: <strong>according to [source]</strong> (según…), <strong>sources say that…</strong>"
        },
        "t2": {
          "heading": "Estilo indirecto: afirmaciones",
          "body": "Al referir lo que alguien dijo, retrocede los tiempos verbales ('backshift'): <strong>Presente → Pasado:</strong> <em>'I am happy.' → She said she was happy.</em> <strong>Pasado → Pasado perfecto:</strong> <em>'I went.' → He said he had gone.</em> <strong>Will → Would:</strong> <em>'I will help.' → She said she would help.</em> <strong>Can → Could:</strong> <em>'I can come.' → He said he could come.</em> Cambia también los pronombres y las expresiones de tiempo: <em>'I'll call you tomorrow' → She said she would call me the next day.</em>"
        },
        "t3": {
          "heading": "Estilo indirecto: preguntas",
          "body": "Para las preguntas indirectas, usa el <strong>orden normal</strong> (sujeto + verbo), NO el orden invertido de pregunta. <strong>Preguntas con wh-:</strong> <em>'Where do you live?' → She asked where I lived.</em> <strong>Preguntas de sí/no:</strong> usa <strong>if / whether</strong>: <em>'Are you coming?' → He asked if/whether I was coming.</em> Nota: NO uses 'do/does/did' en preguntas indirectas: ✗ <em>She asked where did I live.</em> ✓ <em>She asked where I lived.</em>"
        }
      },
      "examples": {
        "e1": "Ella me dijo que la reunión se había cancelado.",
        "e2": "El periodista informó que todavía estaban contando los resultados de las elecciones.",
        "e3": "Él me preguntó adónde iba.",
        "e4": "El periódico dijo que los precios subirían el año que viene.",
        "e5": "Ella me preguntó si había visto las noticias esa mañana.",
        "e6": "Una noticia de última hora informó de que un gran terremoto había azotado la región.",
        "e7": "El primer ministro dijo a los periodistas que la economía estaba mejorando.",
        "e8": "Él anunció que había decidido dimitir de su cargo."
      },
      "flashcards": {
        "f1": "Titular",
        "f2": "Última hora",
        "f3": "Según…",
        "f4": "Ella dijo que…",
        "f5": "Él preguntó si…",
        "f6": "Retroceso de los tiempos verbales",
        "f7": "…where I lived (orden normal, sin 'do')",
        "f8": "Would (will en estilo indirecto)",
        "f9": "Al día siguiente",
        "f10": "Corresponsal"
      },
      "quiz": {
        "q1": "Presente simple → pasado simple en estilo indirecto: 'am' → 'was'.",
        "q2": "'Will' → 'would' en el estilo indirecto.",
        "q3": "Las preguntas indirectas usan pasado y orden normal (sin 'do'): 'where I lived'.",
        "q4": "Breaking news = eventos importantes que ocurren ahora mismo o muy recientemente.",
        "q5": "Las preguntas indirectas de sí/no usan 'if/whether' + sujeto + verbo (sin inversión)."
      }
    },
    "b1-email": {
      "title": "Correos y lenguaje formal",
      "theory": {
        "t1": {
          "heading": "Estructura del correo formal",
          "body": "<strong>Saludo:</strong> <em>Dear Mr/Ms [Apellido],</em> (si conoces el nombre) o <em>Dear Sir/Madam,</em> (si no lo conoces). No uses nombres de pila en correos formales salvo invitación. <strong>Primera línea:</strong> indica tu propósito con claridad: <em>I am writing to enquire about… / I am writing with reference to… / Further to our conversation…</em> <strong>Cuerpo:</strong> da detalles, haz peticiones. <strong>Cierre:</strong> <em>I look forward to hearing from you. / Please do not hesitate to contact me.</em> <strong>Despedida:</strong> <em>Yours sincerely,</em> (cuando conoces el nombre) o <em>Yours faithfully,</em> (con Dear Sir/Madam). Después tu nombre completo."
        },
        "t2": {
          "heading": "Rasgos del lenguaje formal",
          "body": "En los correos formales: <strong>Usa formas completas</strong> (no contracciones): escribe <em>I am</em> no <em>I'm</em>, <em>I would</em> no <em>I'd</em>. <strong>Elige vocabulario formal:</strong> <em>enquire</em> (no <em>ask</em>), <em>commence</em> (no <em>start</em>), <em>require</em> (no <em>need</em>), <em>assist</em> (no <em>help</em>), <em>inform</em> (no <em>tell</em>), <em>receive</em> (no <em>get</em>), <em>request</em> (no <em>ask for</em>). <strong>Sé indirecto y cortés:</strong> <em>I would be grateful if you could…</em> es mucho más cortés que <em>Please send me…</em>"
        },
        "t3": {
          "heading": "Frases clave para correos formales",
          "body": "<strong>Indicar el propósito:</strong> <em>I am writing to enquire about… / I am writing to complain about… / I am writing to apply for… / I am writing to confirm…</em> <strong>Peticiones:</strong> <em>I would be grateful if you could… / Could you please… / I would appreciate it if…</em> <strong>Adjuntos:</strong> <em>Please find attached… / I am attaching…</em> <strong>Disculpas:</strong> <em>I am afraid I will be unable to… / I am sorry to inform you that…</em> <strong>Cierre:</strong> <em>I look forward to hearing from you. / I look forward to your reply. / Please do not hesitate to contact me if you require further information.</em>"
        }
      },
      "examples": {
        "e1": "Le escribo para informarme sobre el puesto anunciado en línea.",
        "e2": "Le agradecería que pudiera enviarme más información.",
        "e3": "Estimado Sr. García, gracias por su correo del 15 de marzo.",
        "e4": "Quedo a la espera de su respuesta a la mayor brevedad posible.",
        "e5": "Adjunto mi CV y carta de presentación como se solicitó.",
        "e6": "En relación con nuestra conversación telefónica, le escribo para confirmar los detalles.",
        "e7": "Lamento informarle de que no podré asistir a la reunión del jueves.",
        "e8": "Si necesita más información, no dude en ponerse en contacto conmigo."
      },
      "flashcards": {
        "f1": "Estimado Sr./Sra.… (destinatario conocido)",
        "f2": "Estimado señor/señora (destinatario desconocido)",
        "f3": "Le escribo para…",
        "f4": "Le agradecería que…",
        "f5": "Adjunto…",
        "f6": "Quedo a la espera de…",
        "f7": "Atentamente (conoce el nombre)",
        "f8": "Le saluda atentamente (no conoce el nombre)",
        "f9": "Lamento… (disculpa formal)",
        "f10": "Informarse / Preguntar (formal)"
      },
      "quiz": {
        "q1": "Regla: Dear + nombre → Yours sincerely. Dear Sir/Madam → Yours faithfully.",
        "q2": "'I am writing to enquire about the position' es formal y profesional.",
        "q3": "'Please find attached' indica al lector que has incluido un documento con el correo.",
        "q4": "Las contracciones ('I'd') y las frases informales no son apropiadas en correos formales.",
        "q5": "'I look forward to hearing from you' es el cierre estándar de un correo formal."
      }
    },
    "b1-feel": {
      "title": "Sentimientos y experiencias",
      "theory": {
        "t1": {
          "heading": "Vocabulario de sentimientos",
          "body": "Emociones básicas: <strong>happy</strong> (feliz), <strong>sad</strong> (triste), <strong>angry</strong> (enfadado), <strong>scared / frightened</strong> (asustado), <strong>surprised</strong> (sorprendido), <strong>excited</strong> (emocionado), <strong>nervous / anxious</strong> (nervioso), <strong>bored</strong> (aburrido), <strong>tired</strong> (cansado), <strong>proud</strong> (orgulloso), <strong>embarrassed</strong> (avergonzado), <strong>disappointed</strong> (decepcionado), <strong>jealous</strong> (celoso), <strong>grateful</strong> (agradecido), <strong>frustrated</strong> (frustrado), <strong>confused</strong> (confundido), <strong>relieved</strong> (aliviado), <strong>lonely</strong> (solo), <strong>content</strong> (satisfecho). Extras avanzados (B2+): <em>melancholy</em> (melancólico), <em>elated</em> (eufórico), <em>apprehensive</em> (aprensivo), <em>overwhelmed</em> (abrumado), <em>nostalgic</em> (nostálgico). <strong>Cuidado: adjetivos en -ed vs -ing.</strong> Los adjetivos terminados en <strong>-ed</strong> describen cómo se siente una persona: <em>I am bored</em> (estoy aburrido). <em>She was interested. We were tired.</em> Los adjetivos terminados en <strong>-ing</strong> describen la cosa o persona que causa el sentimiento: <em>The film was boring</em> (la película era aburrida). <em>The book is interesting. The journey was tiring</em> (agotador). Trampa clásica: <em>I am boring</em> significa 'yo aburro a los demás' — di <em>I am bored</em>."
        },
        "t2": {
          "heading": "Presente perfecto para experiencias de vida",
          "body": "Usa el <strong>presente perfecto (have/has + participio pasado)</strong> para hablar de experiencias de vida sin decir cuándo: <em>Have you ever been to Japan? I have never tried sushi. She has visited over 20 countries. He has won several awards.</em> Con un momento específico → usa el pasado simple: <em>I went to Japan in 2018.</em> Palabras clave con experiencias en presente perfecto: <strong>ever</strong> (en preguntas), <strong>never</strong> (negativo), <strong>already</strong> (antes de lo esperado), <strong>yet</strong> (todavía no)."
        },
        "t3": {
          "heading": "Adjetivos graduables y no graduables",
          "body": "Los <strong>adjetivos graduables</strong> tienen distintos grados y usan <em>very / really</em>: <em>very tired, really happy, quite cold.</em> Los <strong>adjetivos no graduables (extremos)</strong> ya contienen la idea de 'very' y usan <em>absolutely</em>: <em>absolutely exhausted</em> (no 'very exhausted'), <em>absolutely delighted, absolutely terrified, absolutely furious, absolutely freezing.</em> Parejas comunes: scared → terrified, happy → delighted, tired → exhausted, angry → furious, hungry → starving, cold → freezing."
        }
      },
      "examples": {
        "e1": "Llevo viviendo en Santiago tres años.",
        "e2": "¿Has probado alguna vez comida británica tradicional como el asado de domingo?",
        "e3": "Ella estaba absolutamente encantada cuando oyó la noticia.",
        "e4": "Nunca en mi vida me he sentido tan nervioso como antes de ese examen.",
        "e5": "Él se siente muy frustrado cuando no puede comunicar sus ideas con claridad.",
        "e6": "Estoy muy emocionado por mi viaje a Escocia el mes que viene.",
        "e7": "Estábamos absolutamente agotados después de caminar ocho horas por la montaña.",
        "e8": "Ella ha ganado el premio a la mejor profesora tres años seguidos."
      },
      "flashcards": {
        "f1": "Emocionado / Ilusionado",
        "f2": "Nervioso / Ansioso",
        "f3": "Orgulloso",
        "f4": "Avergonzado",
        "f5": "Aliviado",
        "f6": "Absolutamente encantado",
        "f7": "Absolutamente agotado",
        "f8": "¿Has… alguna vez?",
        "f9": "Nunca he…",
        "f10": "Tres años seguidos"
      },
      "quiz": {
        "q1": "'Have you ever been to…?' es la expresión estándar para experiencias de vida. 'Been to' = visitó y regresó. Después de 'have' se necesita el participio pasado: 'went' es pasado simple, y 'go' y 'be' son infinitivos sin conjugar — ninguno puede ir después de 'have'.",
        "q2": "'Absolutely exhausted' es el adjetivo extremo. Nunca digas 'absolutely tired' ni 'very exhausted'.",
        "q3": "Presente perfecto = have/has + participio pasado. 'I have never tried' es correcto.",
        "q4": "'Terrified' es la forma extrema/no graduable de 'scared'. 'Absolutely terrified' = extremadamente asustado.",
        "q5": "El presente perfecto (has visited) habla de la experiencia de vida sin especificar momentos exactos."
      }
    }
  }
};
